name: e_ehson
description: e-Ehson - social donation platform frontend (Material 3, GetX, mock)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  dio: ^5.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_svg: ^1.1.0
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  convex_bottom_bar: ^3.2.0
  image_picker: ^1.1.1
  shared_preferences: ^2.2.0
  confetti: ^0.7.0
  cached_network_image: ^3.2.3
  flutter_slidable: ^0.6.0
  url_launcher: ^6.1.7 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
